- name: Coletar fatos do sistema
  hosts: localhost 
  tasks:
    - name: Coletar informações da máquina
      setup:

    - name: Mostrar todas as informações coletadas
      debug:
        var: ansible_facts
