---
- name: Download PNG image
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Get image using wget
      get_url:
        url: https://avatars.githubusercontent.com/u/129978598?v=4
        dest: /usr/local/bin/celso.png
        mode: 0644

    - name: install updates (Ubuntu)
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy file
      copy:
        src: /usr/local/bin/celso.png
        dest: /home/celso/Documents/
        owner: root
        group: root
        mode: 0644