---
- hosts: GFL
  become: true
  tasks:
    - name: Copie o script para o host
      copy:
        src: SRAAUTOMATOS.54
        dest: /tmp/SRAAUTOMATOS.54
        mode: 0755
    - name: Execute o script
      become: yes
      become_method: sudo
      command: /tmp/SRAAUTOMATOS.54

    - name: Copiar arquivo ada.deb para o Hostname
      copy:
        src: ada-1.7.18-en.i386.lin.deb
        dest: /tmp/ada-1.7.18-en.i386.lin.deb

    - name: Instalar pacote ADA.deb
      become: yes
      become_method: sudo
      command: dpkg -i /tmp/ada-1.7.18-en.i386.lin.deb

    - name: Configurando Ada Agent após a instalação
      become: yes
      become_method: sudo
      shell: |
        cd /opt/automatos/ada/bin
        sudo ./asetup -s -a -s -ialmaden@gflogistica.com.br -bLINUX -ca127.0.0.1:1999 -crhttp:http.vip.automatos.com:80
