---
- name: Checar se o ISAlwaysOn existe no diret처rio
  hosts: MTM
  become: yes
  tasks:
    - name: Checar se o arquivo existe
      stat:
        path: /opt/ISLOnline/ISLAlwaysOn/ISLAlwaysOn
      register: file_result
    - name: Mostrar mensagem se o arquivo existe
      debug:
        msg: "O arquivo existe!"
      when: file_result.stat.exists  # Mostra caso exista
    - name: Mostrar mensagem se o arquivo n찾o existe
      debug:
        msg: "O arquivo n찾o existe"
      when: not file_result.stat.exists  # Mostrar caso n찾o exista
