$ANSIBLE_VAULT;1.1;AES256
66323966333166303030393534303530343164303563383130343162306233636265366130633561
3461313638333135303061346662376665363038656464350a306638646266386562636336363566
32303133363635326633626336623063373639356435643536356234323763613139383739333962
6335346562393635360a353638633230633865353437613132383334393231336235313732383561
35363630613964353830633537336631383061643537343266646265323265613862333362313237
37343464656638306636316531363762323539343738613866653837316561313232646164323230
31636630373339323434643433623861343166393430356235383438643432313466663835373238
65343563613933346230
