---
- hosts: localhost
  become: true
  tasks:
    - name: Instalar AV GFL
      copy:
        src: /home/celso/labs/ansible/playbooks/files/AVGFL.sh
        dest: /tmp/AVGFL.sh
        mode: 0755
    - name: Execute o script
      become: yes
      become_method: sudo
      command: /tmp/AVGFL.sh

      