---
- name: Validar configurações do GDM
  hosts: localhost
  tasks:
    - name: Ensure GDM disable-user-list option is enabled
      command: gsettings set org.gnome.login-screen disable-user-list true

    - name: Ensure GDM screen locks when the user is idle
      command: gsettings set org.gnome.desktop.screensaver lock-enabled true

    - name: Ensure GDM screen locks cannot be overridden
      command: gsettings set org.gnome.desktop.lockdown disable-lock-screen true

    - name: Ensure GDM automatic mounting of removable media is disabled
      command: gsettings set org.gnome.desktop.media-handling automount false

    - name: Ensure GDM disabling automatic mounting of removable media is not overridden
      command: gsettings set org.gnome.desktop.lockdown disable-automount true

    - name: Ensure GDM autorun-never is enabled
      command: gsettings set org.gnome.desktop.media-handling autorun-never true

    - name: Ensure GDM autorun-never is not overridden
      command: gsettings set org.gnome.desktop.lockdown disable-automount-never true
