---
- name: Download PNG image
  hosts: localhost
  become: true
  become_method: sudo
  tasks:

    - name: Copiar arquivo ada.deb para o Hostname
      copy:
        src: ~/ansible/files/SRAAUTOMATOS.46
        dest: /usr/local/bin/

    - name: Copiar arquivo ada.deb para o Hostname
      copy:
        src: ~/ansible/files/ada-1.9.1-en.i386.lin.deb
        dest: /usr/local/bin/  

    

