---
- name: Instalar o Visual Studio Code no Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar dependências
      apt:
        name:
          - wget
          - gpg
        state: present

    - name: Adicionar a chave GPG do repositório do VS Code
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Adicionar o repositório do VS Code
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: present

    - name: Instalar o Visual Studio Code
      apt:
        name: code
        state: latest

    - name: Remover dependências não utilizadas
      apt:
        autoremove: yes
